### ISSUE TITLE
Lane point confidence value

### ISSUE THREAD

**Issue by Yibin122** [czming/RONELD-Lane-Detection#4]
https://github.com/czming/RONELD-Lane-Detection/blob/main/lane_detection_functions.py#L550
Could you explain why you select the confidence value of salient point (not highest confidence point) as lane point confidence? It seems confusing to me you search for the highest confidence point but only use its location.

**Comment by czming** [comment]
Hi, great question! Just to clarify, you're asking why the method searches for a salient point before searching for the highest confidence point while only using the highest confidence point? This is done because some lanes (especially on the TuSimple cross-dataset validation) have some low-confidence noise that is way off the actual lane which we are trying to ignore by finding a salient point before proceeding to search for the lane point.

![00020_4_avg](https://user-images.githubusercontent.com/16664600/100336593-55faa900-3011-11eb-8627-c8c86d052951.png)

The line highlighted in your link is storing the confidence of the highest confidence point (also a lane point) which is used later in the weighted least squares linear regression.

**Comment by Yibin122** [comment]
Thanks for your explanation about the idea of salient point.

But what I don't understand is that you are still using the confidence value of that salient point:
confidence.append(lane_image[row][column])

Why not the highest confidence point ??
confidence.append(lane_image[point[1]][point[0]])

**Comment by czming** [comment]
Ok, I get what you mean now, yeah that's a mistake, I'll fix it up. Thanks for pointing it out!
