### ISSUE TITLE
get_all_lanes

### ISSUE THREAD

**Issue by nolehuan** [czming/RONELD-Lane-Detection#6]
```
        if len(longest_lane) >= MIN_CURVE_LANE_LENGTH and correlation_linear(longest_lane) < \
                correlation_linear(longest_lane[initial_section:]):
            curve = True
        else:
            # clear outliers if not a curve
            longest_lane, confidence = clear_outliers(longest_lane, confidence,
                                                      iterations=1, to_dump=0.2)
            avg_confidence = rms(confidence)

        gradient, y_intercept = linear_regression_matrix(longest_lane, confidence)
        curr_lanes[i] = {"lane": (gradient, y_intercept), "image": i, "curve": curve,
                         "points": longest_lane, "avg_confidence": avg_confidence,
                         "confidence": confidence}
```

Hi, could u please tell me why u apply the linear regression matrix function to the sovling process of the curve lane, which is used upon the straight lane as ur decription in the paper.

![image](https://user-images.githubusercontent.com/56197186/111470241-9c137e00-8762-11eb-9f6b-8a6c7f5afd87.png)

and the results of testing my own training data using ERFNet are very poor
![image](https://user-images.githubusercontent.com/56197186/111473744-52c52d80-8766-11eb-85e0-c68af0b55e59.png)

**Comment by czming** [comment]
Hello, thanks for checking out the code! We apply the linear regression function to the curved lanes so that we can still use them for lane tracking in succeeding frames so that the curved and straight lanes can still be compared between the different frames. When the lanes are plotted, they are using the quadratic spline in the plot_curves function.

For the ERFNet results, it doesn't really help the exact example that you gave, but you might want to adjust the lane_ratio argument when calling roneld_lane_detection to adjust the height of the lane. The default argument 0 would map the lane to the top lane point found (which I think is rather interesting if your example uses that since that means ERFNet is outputting a non-zero probability for a point in the sky that RONELD found as a lane point). Maybe if you could share the probability map outputs for the lanes from ERFNet it might help me better understand the issue? Thanks!

Hope that helps!

Edit: I think I might have an idea for how ERFNet might be giving that output. Is the semantic segmentation probability map output for the whole image? Because ENet-SAD output had a similar issue because if I remember correctly, it looked only at the bottom 60% of the image, so we had to add the top 40% of background pixels at the top of image to match the images to be standard across different models since some models might remove different proportions of background pixels. RONELD assumes that the probability map output is for the whole image

**Comment by nolehuan** [comment]
thanks for ur careful reply, i'll add the background pixels and test again
