### ISSUE TITLE
Query : Is it possible to use latest lane detection like Clrnet (clrnet: cross layer refinement network for lane detection)

### ISSUE THREAD

**Issue by waqarsqureshi** [czming/RONELD-Lane-Detection#7]
Hi,
I was curious to know if we can use the detection of lanes from the Clrnet for lane tracking. It outputs foreground and background probabilities, Lane priors, starting point and the angle with the horizontal.

**Comment by waqarsqureshi** [comment]
Also, i am more curious about finding the outer lane of the road instead of the active lanes. I tend to have a different application for it.

**Comment by czming** [comment]
Hello! Thank you for your question, with regards to your first question on the applicability of RONELD to other methods, currently it can generally support models that output a semantic segmentation map, which doesn't seem to be the case with CLRNet though I can imagine that the lane weighing procedure could be generalized to weigh lanes that are outputted by CLRNet (some modules within RONELD such as finding lane keypoints in the segmentation map can be disregarded since it seems like CLRNet already outputs lanes directly).

With regards to your second question about finding the outer lanes, I don't think RONELD is well-suited for that task as it presently gives higher weightage to ego lanes. However, if all lanes are given the same weight (lane_priority with all keys mapped to 1, presently lane_priority = {0: 1, 1: math.e ** 2, 2: math.e ** 2, 3: 1}), then it might be possible to just return the top k lanes (where k is the number of lanes that you want to output), though I'm uncertain about how good the results will be.

Hope that helps!

**Comment by waqarsqureshi** [comment]
The first way forward would be to test the semantic segmentation-based method on my test images along with your tracking and see how it works. I will come back with results and more queries later then.
